excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://maegul.github.io
title: maegul
tagline: A Test
description: A test of TinyPress
author: Errol Lloyd
email: errolkjlloyd@gmail.com
paginate: 3
